### ISSUE TITLE
Change public/private status after first time time sign up

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview-standup#117] opened 2020-01-28 21:58 UTC
Right now users can only make this choice at the 1st sign up. The decision to go from private to public is irreversible. Do we want to change that? This needs design.

But at the very least we should allow users who preserved the private identity to go public later one, while now there is no way to do that.

**Comment by dasaderi** [comment] 2020-03-11 20:11
Need to improve current UI as currently black long text box explaining the choices covering buttons.

**Comment by murkatr** [comment] 2020-06-10 03:09
This is a duplicate of #108, so closing this issue.

**Closed by murkatr** 2020-06-10 03:09 UTC
Labels: priority / medium, scope / design, scope / development, type / enhancement
